apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: website
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: /helm/node-helm
      version: "0.x.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
      interval: 1m