apiVersion: batch/v1
kind: CronJob
metadata:
  name: websitecron
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nodecron
            image: nodecron
            imagePullPolicy: Never
            env:
            - name: PORT
              value: "8000"
            - name: URL
              value: "node-entrypoint.default.svc.cluster.local"
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"