apiVersion: batch/v1
kind: CronJob
metadata:
  name: websitecron
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curlimage
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - curl -X GET http://node-entrypoint.default.svc.cluster.local:8000/count
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"